version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - LANGSMITH_API_KEY=${LANGSMITH_API_KEY}
      - LANGSMITH_PROJECT=aml-investigation
      - LANGSMITH_TRACING=true
      - MEM0_API_KEY=${MEM0_API_KEY}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - DATABASE_URL=sqlite:///./data/aml_database.db
      - VECTOR_DB_PATH=/app/data/kyc_vectordb
      - DEBUG=false
      - LOG_LEVEL=INFO
    volumes:
      - ./data:/app/data
      - ./app:/app/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - postgres
    networks:
      - aml-network

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=aml_db
      - POSTGRES_USER=aml_user
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-aml_password}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - aml-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - aml-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
    networks:
      - aml-network

volumes:
  postgres_data:
  redis_data:

networks:
  aml-network:
    driver: bridge
